FROM node:18-alpine

# Instalar MongoDB
# RUN apk add --no-cache mongodb

# Instalar PNPM
RUN npm install -g pnpm

# Establecer directorio de trabajo
WORKDIR /app

# Copiar archivos de paquetes de instalación
COPY package.json package-lock*.json ./

# Instalar dependencias
RUN pnpm install

# Copiar archivos de aplicación
COPY . .

# Exponer puerto de la aplicación
EXPOSE 3000

# Iniciar MongoDB y la aplicación
CMD [ "npm", " run dev" ]

