version: '3'
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: express-server
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - mongodb
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
