# Utiliza la imagen base de MongoDB
FROM mongo:4

# Establece las variables de entorno para la inicialización de la base de datos
ENV MONGO_INITDB_ROOT_USERNAME=admin
ENV MONGO_INITDB_ROOT_PASSWORD=password

# Expone el puerto 27017 para acceder a la base de datos
EXPOSE 27017
